version: "3.3"

volumes:
    postgres_data:

services:
  golang:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./assets/:/go/assets/
    environment:
      - PORT=${GOLANG_PORT}
      - ACCESS_EXPIRES=${GOLANG_ACCESS_EXPIRES}
      - REFRESH_EXPIRES=${GOLANG_REFRESH_EXPIRES}
      - SECRET_KEY=${GOLANG_SECRET_KEY}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DB=${POSTGRES_DB}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_SSLMODE=${POSTGRES_SSLMODE}
    command: go run cmd/app/main.go

  postgres:
    restart: always
    image: "postgres:latest"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
